// <auto-generated />
using System;
using EWTSS_DESKTOP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EWTSS_DESKTOP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313161434_AddScenarioHierarchyModels")]
    partial class AddScenarioHierarchyModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.AreaOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Altitude")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int")
                        .HasColumnName("scenario_id");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("area_operation", (string)null);
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.AreaOperationPolygon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Altitude")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AreaOperationId")
                        .HasColumnType("int")
                        .HasColumnName("area_operation_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("AreaOperationId");

                    b.ToTable("area_operation_polygon", (string)null);
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.Cc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CcName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cc_name");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("line_id");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("cc", (string)null);
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.Emitter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AntennaType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("antenna_type");

                    b.Property<double?>("Bandwidth")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("EmitterType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("emitter_type");

                    b.Property<double?>("Gain")
                        .HasColumnType("double");

                    b.Property<string>("HopInterPeriodUnit")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hop_inter_period_unit");

                    b.Property<double?>("HopInterPeriodValue")
                        .HasColumnType("double")
                        .HasColumnName("hop_inter_period_value");

                    b.Property<string>("HopPeriodUnit")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hop_period_unit");

                    b.Property<double?>("HopPeriodValue")
                        .HasColumnType("double")
                        .HasColumnName("hop_period_value");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("line_id");

                    b.Property<string>("ModeType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mode_type");

                    b.Property<string>("ModulationType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("modulation_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatternType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pattern_type");

                    b.Property<string>("PlatformType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("platform_type");

                    b.Property<string>("Polarization")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("PowerTransmitted")
                        .HasColumnType("double")
                        .HasColumnName("power_transmitted");

                    b.Property<double?>("ScanRate")
                        .HasColumnType("double")
                        .HasColumnName("scan_rate");

                    b.Property<double?>("StartFrequencyValue")
                        .HasColumnType("double")
                        .HasColumnName("start_frequency_value");

                    b.Property<double?>("StopFrequencyValue")
                        .HasColumnType("double")
                        .HasColumnName("stop_frequency_value");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("emitter", (string)null);
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AntennaHeight")
                        .HasColumnType("int")
                        .HasColumnName("antenna_height");

                    b.Property<string>("AntennaType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("antenna_type");

                    b.Property<int>("CcId")
                        .HasColumnType("int")
                        .HasColumnName("cc_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("entity_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Polarization")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ScanType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("scan_type");

                    b.Property<double?>("StartFrequencyValue")
                        .HasColumnType("double")
                        .HasColumnName("start_frequency_value");

                    b.Property<double?>("StopFrequencyValue")
                        .HasColumnType("double")
                        .HasColumnName("stop_frequency_value");

                    b.HasKey("Id");

                    b.HasIndex("CcId");

                    b.ToTable("entity", (string)null);
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.EntityPolygon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("entity_polygon", (string)null);
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("feature", (string)null);
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPermit")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("RoleId");

                    b.ToTable("role_permission", (string)null);
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<DateTime?>("ExecuteDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("execute_date");

                    b.Property<string>("ExecuteRun")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("execute_run");

                    b.Property<TimeSpan?>("ExecuteTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("execute_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ScenarioStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("scenario_status");

                    b.Property<string>("ScenarioType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("scenario_type");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<string>("StartStop")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("start_stop");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_on");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("scenario", (string)null);
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.ScenarioLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaOperationId")
                        .HasColumnType("int")
                        .HasColumnName("area_operation_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("line_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("AreaOperationId");

                    b.ToTable("line", (string)null);
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_on");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.AreaOperation", b =>
                {
                    b.HasOne("EWTSS_DESKTOP.Core.Models.Scenario", "Scenario")
                        .WithMany("AreaOperations")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.AreaOperationPolygon", b =>
                {
                    b.HasOne("EWTSS_DESKTOP.Core.Models.AreaOperation", "AreaOperation")
                        .WithMany("Polygons")
                        .HasForeignKey("AreaOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaOperation");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.Cc", b =>
                {
                    b.HasOne("EWTSS_DESKTOP.Core.Models.ScenarioLine", "Line")
                        .WithMany("Ccs")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.Emitter", b =>
                {
                    b.HasOne("EWTSS_DESKTOP.Core.Models.ScenarioLine", "Line")
                        .WithMany("Emitters")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.Entity", b =>
                {
                    b.HasOne("EWTSS_DESKTOP.Core.Models.Cc", "Cc")
                        .WithMany("Entities")
                        .HasForeignKey("CcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cc");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.EntityPolygon", b =>
                {
                    b.HasOne("EWTSS_DESKTOP.Core.Models.Entity", "Entity")
                        .WithMany("Polygons")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.RolePermission", b =>
                {
                    b.HasOne("EWTSS_DESKTOP.Core.Models.Feature", "Feature")
                        .WithMany("Permissions")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWTSS_DESKTOP.Core.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.Scenario", b =>
                {
                    b.HasOne("EWTSS_DESKTOP.Core.Models.User", "User")
                        .WithMany("CreatedScenarios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.ScenarioLine", b =>
                {
                    b.HasOne("EWTSS_DESKTOP.Core.Models.AreaOperation", "AreaOperation")
                        .WithMany("Lines")
                        .HasForeignKey("AreaOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaOperation");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.User", b =>
                {
                    b.HasOne("EWTSS_DESKTOP.Core.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.AreaOperation", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Polygons");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.Cc", b =>
                {
                    b.Navigation("Entities");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.Entity", b =>
                {
                    b.Navigation("Polygons");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.Feature", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.Scenario", b =>
                {
                    b.Navigation("AreaOperations");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.ScenarioLine", b =>
                {
                    b.Navigation("Ccs");

                    b.Navigation("Emitters");
                });

            modelBuilder.Entity("EWTSS_DESKTOP.Core.Models.User", b =>
                {
                    b.Navigation("CreatedScenarios");
                });
#pragma warning restore 612, 618
        }
    }
}
